function phi = from_shear_phase(X, Y, phi_shear, n_shear, i_noll)
%FROM_SHEAR_PHASE Reconstruct phase from shear phase using differential Zernike.
%
%   phi = from_shear_phase(X, Y, phi_shear, n_shear)
%   phi = from_shear_phase(X, Y, phi_shear, n_shear, i_noll)
%
% INPUT
%   X, Y
%       Coordinate matrices generated by meshgrid.
%
%   phi_shear
%       Shear phase:
%
%       phi_shear(:,:,1) =
%           phi(x + n_shear(1)*dx, y) - phi(x,y)
%
%       phi_shear(:,:,2) =
%           phi(x, y + n_shear(2)*dx) - phi(x,y)
%
%   n_shear
%       Shear amount in pixels:
%
%           [nx, ny]
%
%   i_noll
%       Noll indices of Zernike modes.
%       Default: 1:45
%
% OUTPUT
%   phi
%       Reconstructed phase.
%
% -------------------------------------------------------------------------

%% Parameters

if nargin < 5
    i_noll = 1:45;
end

assert(ndims(phi_shear) == 3 && size(phi_shear,3) == 2, ...
    'phi_shear must have size [Ny, Nx, 2].');

assert(isequal(size(X), size(Y)), ...
    'X and Y must have the same size.');

assert(isequal(size(X), size(phi_shear(:,:,1))), ...
    'X/Y and phi_shear must have compatible sizes.');

%% Coordinate sampling

dx = median(diff(X(1,:)));
dy = median(diff(Y(:,1)));

sx = n_shear(1) * dx;
sy = n_shear(2) * dy;

%% ------------------------------------------------------------------------
% Generate Zernike basis on the original aperture
% -------------------------------------------------------------------------

[Z, ~, ~, ~] = rect_zernike(X, Y, i_noll);

n_mode = numel(i_noll);

%% ------------------------------------------------------------------------
% Evaluate shifted Zernike modes
%
% We use interpolation so that the SAME Zernike basis is used at
% (x+s,y) and (x,y+s).
% -------------------------------------------------------------------------

Zx = zeros(size(Z), 'like', Z);
Zy = zeros(size(Z), 'like', Z);

Xx = X + sx;
Yx = Y;

Xy = X;
Yy = Y + sy;

% Valid regions
valid_x = Xx >= min(X(:)) & Xx <= max(X(:)) & ...
          Yx >= min(Y(:)) & Yx <= max(Y(:));

valid_y = Xy >= min(X(:)) & Xy <= max(X(:)) & ...
          Yy >= min(Y(:)) & Yy <= max(Y(:));

for k = 1:n_mode

    Zk = Z(:,:,k);

    % x shear
    Zx(:,:,k) = interp2( ...
        X, Y, Zk, ...
        Xx, Yx, ...
        'linear', NaN);

    % y shear
    Zy(:,:,k) = interp2( ...
        X, Y, Zk, ...
        Xy, Yy, ...
        'linear', NaN);
end

%% ------------------------------------------------------------------------
% Differential Zernike basis
% -------------------------------------------------------------------------

Dx = Zx - Z;
Dy = Zy - Z;

%% ------------------------------------------------------------------------
% Remove piston mode
%
% Shearing completely eliminates piston:
%
%   (C + phi(x+s)) - (C + phi(x))
%       = phi(x+s) - phi(x)
%
% Therefore the piston coefficient cannot be determined.
%
% We simply remove Noll index 1 from the reconstruction.
% -------------------------------------------------------------------------

piston = (i_noll == 1);

i_fit = find(~piston);

Dx_fit = Dx(:,:,i_fit);
Dy_fit = Dy(:,:,i_fit);

%% ------------------------------------------------------------------------
% Build least-squares system
% -------------------------------------------------------------------------

phase_x = phi_shear(:,:,1);
phase_y = phi_shear(:,:,2);

mask_x = valid_x & isfinite(phase_x);
mask_y = valid_y & isfinite(phase_y);

% Also reject invalid differential basis values
for k = 1:numel(i_fit)
    mask_x = mask_x & isfinite(Dx_fit(:,:,k));
    mask_y = mask_y & isfinite(Dy_fit(:,:,k));
end

Ax = reshape(Dx_fit(repmat(mask_x,1,1,numel(i_fit))), ...
            [], numel(i_fit));

Ay = reshape(Dy_fit(repmat(mask_y,1,1,numel(i_fit))), ...
            [], numel(i_fit));

bx = phase_x(mask_x);
by = phase_y(mask_y);

A = [Ax; Ay];
b = [bx; by];

%% ------------------------------------------------------------------------
% Remove possible NaN/Inf
% -------------------------------------------------------------------------

valid = all(isfinite(A),2) & isfinite(b);

A = A(valid,:);
b = b(valid);

%% ------------------------------------------------------------------------
% Least-squares reconstruction
% -------------------------------------------------------------------------

% Use QR / backslash instead of inv(A'*A)
coef_fit = A \ b;

%% ------------------------------------------------------------------------
% Construct reconstructed phase
% -------------------------------------------------------------------------

coef = zeros(n_mode,1);
coef(i_fit) = coef_fit;

phi = zeros(size(X));

for k = 1:n_mode
    phi = phi + coef(k) * Z(:,:,k);
end

end
