function phi = from_shear_phase(X, Y, phi_shear, n_shear, i_noll)
%FROM_SHEAR_PHASE Reconstruct phase from multiple 2D shear phases
%using differential Zernike.
%
%   phi = from_shear_phase(X, Y, phi_shear, n_shear)
%   phi = from_shear_phase(X, Y, phi_shear, n_shear, i_noll)
%
% INPUT
%   X, Y
%       Coordinate matrices generated by meshgrid.
%
%   phi_shear
%       Multiple 2D shear phases.
%
%       size(phi_shear) = [n_row, n_col, n]
%
%       The k-th shear phase is defined as
%
%           phi_shear(:,:,k) =
%               phi(x + n_shear(1,1,k)*dx,
%                   y + n_shear(1,2,k)*dy)
%               - phi(x,y)
%
%   n_shear
%       Shear amount in pixels.
%
%       size(n_shear) = [1, 2, n]
%
%       For the k-th shear:
%
%           n_shear(1,1,k) = nx
%           n_shear(1,2,k) = ny
%
%       The physical shear is
%
%           sx = nx * dx
%           sy = ny * dy
%
%   i_noll
%       Noll indices of Zernike modes.
%       Default: 1:45
%
% OUTPUT
%   phi
%       Reconstructed phase.
%
% -------------------------------------------------------------------------

%% Parameters

if nargin < 5
    i_noll = 1:45;
end

%% ------------------------------------------------------------------------
% Check input dimensions
% -------------------------------------------------------------------------

assert(ismatrix(X) && ismatrix(Y), ...
    'X and Y must be 2D matrices.');

assert(isequal(size(X), size(Y)), ...
    'X and Y must have the same size.');

[n_row, n_col] = size(X);

assert(ndims(phi_shear) == 3, ...
    'phi_shear must be a 3D matrix with size [n_row, n_col, n].');

assert(size(phi_shear,1) == n_row && ...
       size(phi_shear,2) == n_col, ...
    'phi_shear must have size [n_row, n_col, n].');

n_shear_count = size(phi_shear, 3);

assert(isequal(size(n_shear), [1, 2, n_shear_count]), ...
    'n_shear must have size [1, 2, n].');

%% ------------------------------------------------------------------------
% Coordinate sampling
% -------------------------------------------------------------------------

dx = median(diff(X(1,:)));
dy = median(diff(Y(:,1)));

%% ------------------------------------------------------------------------
% Generate Zernike basis on the original aperture
% -------------------------------------------------------------------------

Z = rect_zernike(X, Y, i_noll);

n_mode = numel(i_noll);

%% ------------------------------------------------------------------------
% Remove piston mode
% -------------------------------------------------------------------------

piston = (i_noll == 1);

i_fit = find(~piston);

assert(~isempty(i_fit), ...
    'No non-piston Zernike modes are selected.');

n_fit = numel(i_fit);

D_fit = Z(:,:,i_fit);

%% ------------------------------------------------------------------------
% Build least-squares system for all shear measurements
% -------------------------------------------------------------------------
%
% For each shear k:
%
%     D_k(:,:,j) =
%         Z_j(x + sx_k, y + sy_k) - Z_j(x,y)
%
% Then stack all measurements:
%
%     A = [A_1
%          A_2
%          ...
%          A_n]
%
%     b = [b_1
%          b_2
%          ...
%          b_n]
%
% -------------------------------------------------------------------------

A_list = cell(n_shear_count, 1);
b_list = cell(n_shear_count, 1);

for k = 1:n_shear_count

    %% -------------------------------------------------------------
    % Physical shear
    % --------------------------------------------------------------

    sx = n_shear(1,1,k) * dx;
    sy = n_shear(1,2,k) * dy;

    X_shift = X + sx;
    Y_shift = Y + sy;

    %% -------------------------------------------------------------
    % Valid shifted coordinates
    % --------------------------------------------------------------

    valid_shift = ...
        X_shift >= min(X(:)) & X_shift <= max(X(:)) & ...
        Y_shift >= min(Y(:)) & Y_shift <= max(Y(:));

    %% -------------------------------------------------------------
    % Evaluate shifted Zernike modes
    % --------------------------------------------------------------

    Z_shift = NaN(n_row, n_col, n_fit, 'like', Z);

    for j = 1:n_fit

        Zk = Z(:,:,i_fit(j));

        Z_shift(:,:,j) = interp2( ...
            X, Y, Zk, ...
            X_shift, Y_shift, ...
            'linear', NaN);

    end

    %% -------------------------------------------------------------
    % Differential Zernike basis
    % -------------------------------------------------------------

    D = Z_shift - Z(:,:,i_fit);

    %% -------------------------------------------------------------
    % Shear phase measurement
    % -------------------------------------------------------------

    phase_k = phi_shear(:,:,k);

    %% -------------------------------------------------------------
    % Construct valid mask
    % -------------------------------------------------------------

    mask = valid_shift & isfinite(phase_k);

    for j = 1:n_fit
        mask = mask & isfinite(D(:,:,j));
    end

    %% -------------------------------------------------------------
    % Convert to linear system
    % -------------------------------------------------------------

    n_valid = nnz(mask);

    A_k = zeros(n_valid, n_fit, 'like', D);
    b_k = phase_k(mask);

    for j = 1:n_fit
        Dj = D(:,:,j);
        A_k(:,j) = Dj(mask);
    end

    %% -------------------------------------------------------------
    % Remove possible NaN / Inf
    % -------------------------------------------------------------

    valid = isfinite(b_k) & all(isfinite(A_k), 2);

    A_k = A_k(valid,:);
    b_k = b_k(valid);

    A_list{k} = A_k;
    b_list{k} = b_k;

end

%% ------------------------------------------------------------------------
% Combine all shear measurements
% -------------------------------------------------------------------------

A = vertcat(A_list{:});
b = vertcat(b_list{:});

if isempty(A)
    error('No valid pixels are available for reconstruction.');
end

%% ------------------------------------------------------------------------
% Numerical rank / conditioning information
% -------------------------------------------------------------------------

fprintf('Number of shear measurements : %d\n', n_shear_count);
fprintf('Number of Zernike modes      : %d\n', n_fit);
fprintf('Number of equations          : %d\n', size(A,1));
fprintf('Numerical rank               : %d\n', rank(A));
fprintf('Condition number             : %.3e\n', cond(A));

%% ------------------------------------------------------------------------
% Least-squares reconstruction
% -------------------------------------------------------------------------

coef_fit = A \ b;

%% ------------------------------------------------------------------------
% Construct complete coefficient vector
% -------------------------------------------------------------------------

coef = zeros(n_mode, 1, 'like', coef_fit);

coef(i_fit) = coef_fit;

%% ------------------------------------------------------------------------
% Reconstruct phase
% -------------------------------------------------------------------------

phi = zeros(size(X), 'like', coef_fit);

for k = 1:n_mode
    phi = phi + coef(k) * Z(:,:,k);
end

end
