function [Z, dZdX, dZdY, U] = rect_zernike(X, Y, i_noll)
%RECT_ZERNIKE
% Zernike polynomials orthonormalized on a rectangular aperture.
%
%   [Z, dZdX, dZdY, U] = rect_zernike(X, Y, i_noll)
%
% INPUT
%   X, Y
%       Coordinate matrices generated by meshgrid.
%
%   i_noll
%       Noll indices of required modes.
%
% OUTPUT
%   Z
%       Orthogonalized Zernike modes.
%       Size: [size(X), numel(i_noll)]
%
%   dZdX
%       dZ/dX, with respect to the original X coordinate.
%
%   dZdY
%       dZ/dY, with respect to the original Y coordinate.
%
%   U
%       Transformation matrix:
%
%           H = Z_original * U
%
%       where H is orthonormal on the rectangular aperture.
%
%       The normalization is
%
%           mean(H_i .* H_j) = delta_ij
%
%       over the aperture.
%
% -------------------------------------------------------------------------

%% Input check

if nargin ~= 3
    error('Usage: [Z,dZdX,dZdY,U] = rect_zernike(X,Y,i_noll)');
end

if ~isequal(size(X), size(Y))
    error('X and Y must have the same size.');
end

if ~isnumeric(X) || ~isnumeric(Y)
    error('X and Y must be numeric.');
end

i_noll = i_noll(:).';

if any(i_noll < 1) || any(i_noll ~= round(i_noll))
    error('i_noll must contain positive integer Noll indices.');
end

J = max(i_noll);

%% Aperture mask

mask = isfinite(X) & isfinite(Y);

if nnz(mask) < J
    error('Too few sampling points.');
end

%% ========================================================================
% Coordinate normalization
%
% Move aperture centroid to origin and normalize by maximum radius.
% ========================================================================

xc = mean(X(mask));
yc = mean(Y(mask));

Xc = X - xc;
Yc = Y - yc;

rho = sqrt(Xc.^2 + Yc.^2);

rho_max = max(rho(mask));

if rho_max <= 0
    error('Invalid aperture.');
end

x = Xc / rho_max;
y = Yc / rho_max;

%% ========================================================================
% Generate original Zernike basis
% ========================================================================

Npix = nnz(mask);

Z0    = zeros(Npix, J);
dX0   = zeros(Npix, J);
dY0   = zeros(Npix, J);

for j = 1:J

    [n, m] = noll_index(j);

    [Zj, dZjdx, dZjdy] = ...
        zernike_cartesian(n, m, x(mask), y(mask));

    Z0(:,j)  = Zj(:);
    dX0(:,j) = dZjdx(:);
    dY0(:,j) = dZjdy(:);

end

%% ========================================================================
% Modified Gram-Schmidt / QR orthogonalization
%
% We want
%
%       mean(H' * H) = I
%
% i.e.
%
%       H' * H = Npix * I
%
% ========================================================================

Q = zeros(Npix, J);
R = zeros(J, J);

for k = 1:J

    v = Z0(:,k);

    % Modified Gram-Schmidt
    for j = 1:k-1

        R(j,k) = (Q(:,j)' * v) / Npix;

        v = v - R(j,k) * Q(:,j);

    end

    R(k,k) = sqrt((v' * v) / Npix);

    if R(k,k) < 1e-12

        error(['Zernike basis becomes numerically dependent at mode ', ...
               num2str(k), '. Reduce the number of modes or increase ', ...
               'sampling density.']);

    end

    Q(:,k) = v / R(k,k);

end

%% ========================================================================
% Q has:
%
%       mean(Q_i .* Q_j) = delta_ij
%
% Therefore Q itself is already normalized.
%
% Transformation:
%
%       H = Z0 * U
%
% and
%
%       U = inv(R)
%
% ========================================================================

U = inv(R);

H = Z0 * U;

dHdx = dX0 * U;
dHdy = dY0 * U;

%% ========================================================================
% Restore image dimensions
% ========================================================================

Zall  = zeros(numel(X), J);
dXall = zeros(numel(X), J);
dYall = zeros(numel(X), J);

idx = find(mask);

Zall(idx,:)  = H;
dXall(idx,:) = dHdx;
dYall(idx,:) = dHdy;

Zall  = reshape(Zall,  [size(X), J]);
dXall = reshape(dXall, [size(X), J]);
dYall = reshape(dYall, [size(X), J]);

%% ========================================================================
% Convert derivatives from normalized coordinates to physical coordinates
%
%       x = (X-Xc)/rho_max
%
% Therefore
%
%       d/dX = 1/rho_max * d/dx
%
% ========================================================================

dXall = dXall / rho_max;
dYall = dYall / rho_max;

%% ========================================================================
% Return requested modes
% ========================================================================

Z    = Zall(:,:,i_noll);
dZdX = dXall(:,:,i_noll);
dZdY = dYall(:,:,i_noll);

end


%% ========================================================================
% Noll index
% ========================================================================

function [n, m] = noll_index(j)

n = 0;
count = 0;

while j > count + n + 1

    count = count + n + 1;
    n = n + 1;

end

k = j - count;

if mod(n,2) == 0

    % Even n:
    %
    % n = 0 :  0
    % n = 2 :  0 -2 2
    % n = 4 :  0 -2 2 -4 4

    if k == 1

        m = 0;

    else

        kk = k - 1;

        if mod(kk,2) == 1
            m = -2 * ceil(kk/2);
        else
            m =  2 * (kk/2);
        end

    end

else

    % Odd n:
    %
    % n = 1 : -1 1
    % n = 3 : -3 -1 1 3
    % n = 5 : -5 -3 -1 1 3 5

    m = -n + 2*(k-1);

end

end


%% ========================================================================
% Cartesian Zernike polynomial
% ========================================================================

function [Z, dZdx, dZdy] = zernike_cartesian(n, m, x, y)

ma = abs(m);

Z    = zeros(size(x));
dZdx = zeros(size(x));
dZdy = zeros(size(x));

r2 = x.^2 + y.^2;

z_complex = x + 1i*y;

for k = 0:(n-ma)/2

    coeff = (-1)^k * ...
        factorial(n-k) / ...
        (factorial(k) * ...
        factorial((n+ma)/2-k) * ...
        factorial((n-ma)/2-k));

    p = n - 2*k;

    h = (p-ma)/2;

    %% Angular term

    if ma == 0

        A = ones(size(x));

        dAx = zeros(size(x));
        dAy = zeros(size(x));

    else

        zm = z_complex.^ma;

        if ma == 1
            zm1 = ones(size(x));
        else
            zm1 = z_complex.^(ma-1);
        end

        if m > 0

            A = real(zm);

            dAx = ma * real(zm1);
            dAy = -ma * imag(zm1);

        else

            A = imag(zm);

            dAx = ma * imag(zm1);
            dAy = ma * real(zm1);

        end

    end

    %% Radial term

    if h == 0

        B = ones(size(x));

        dBx = zeros(size(x));
        dBy = zeros(size(x));

    else

        B = r2.^h;

        Bm1 = r2.^(h-1);

        dBx = 2*h*x .* Bm1;
        dBy = 2*h*y .* Bm1;

    end

    %% Accumulate

    Z = Z + coeff * A .* B;

    dZdx = dZdx + coeff * ...
        (dAx .* B + A .* dBx);

    dZdy = dZdy + coeff * ...
        (dAy .* B + A .* dBy);

end

end
